// High-level "personality" of a level's track. Drives two things in
// TrackGenerator: the shape of the underlying rolling hills (each archetype
// warps the base waveform differently) and -- when a level is (re)generated by
// GenerateLevelBatch -- which signature features get scattered on top.
//
// Each archetype leans on a different premium creature's Heart action, so
// picking the right passenger for the level actually matters:
//   RollingHills - calm warm-up, no strong lean
//   Switchback   - sharp back-to-back turns  -> Squirrel (Tight Turn)
//   Airborne     - abrupt launch crests      -> Owl (Airtime)
//   Plunges      - long steep descents       -> Fox (Speed Burst)
//   Whoops       - rapid-fire washboard bumps-> Dragon (Near Miss)
//   Mixed        - a bit of everything        -> whole roster / finale levels
//
// Standalone file (not nested), matching PickupType/PowerUpType/HeartActionType.
public enum TrackArchetype
{
    RollingHills,
    Switchback,
    Airborne,
    Plunges,
    Whoops,
    Mixed
}
